### ISSUE TITLE
.

### ISSUE THREAD

**Issue by moutafatin1** [CaptainCodeman/sveltekit-example#12]
.

**Comment by alteredorange** [comment]
There's a short time where you don't know if the user is logged in, needs to re-login, etc. I might hit your site, and have logged in before, but that's not "known" instantly. After firebase resolves whether I'm logged in, logged out, or have never logged in, I'm now "known". It's mostly so you can have a loading animation while auth negotiates.

**Comment by CaptainCodeman** [comment]
That's correct.

As an alternative, instead of using a flag, you could also have the store contain a promise which would be unresolved until the status is known, and then resolved with a user object if authenticated or null of not.

That can play nicely with the `{#await $auth}` block in Svelte templates but ultimately provides the same functionality template-wise.

But a promise can make it easier if you need to wait for auth status to settle elsewhere before doing something, perhaps in another derived store that fetches data for example.

**Comment by moutafatin1** [comment]
Thank you.

**Comment by CaptainCodeman** [comment]
@moutafatin1 FYI: deleting the original question is bad etiquette.
